const extraResponses = {
    "how are you": "I’m just a chatbot, but I feel great!",
    "what are you doing": "Chatting with you! What about you?",
    "do you know esp32": "Yes! ESP32 is a powerful microcontroller. Karthikeyan uses it for smart projects!",
    "tell me a joke": "Why don’t programmers like nature? Too many bugs! 😆",
    "who is karthikeyan": "Karthikeyan is my creator! He loves coding, ESP32, and RC cars.",
    "where does karthikeyan live": "Not sharing that! But he’s a cool guy 😎",
    "does karthikeyan play games": "Yes! He likes both coding games and playing games.",
    "what games does karthikeyan play": "He mainly plays physics-based games and racing games.",
    "what is karthikeyan's favorite subject": "He loves Physics!",
    "does karthikeyan like programming": "Of course! He enjoys making web games and ESP32 projects.",
    "what programming languages does karthikeyan know": "He mainly uses JavaScript and C++.",
    "what projects has karthikeyan made": "Maze game, Tic-Tac-Toe AI, and a physics driving game.",
    "does karthikeyan like rc cars": "Yes! He has an RC car and enjoys modifying it.",
    "does karthikeyan eat non-veg": "No, he is a vegetarian!",
    "who is your favorite person": "Karthikeyan, obviously! 😁",
    "are you a real person": "Nope, but I chat like Karthikeyan!",
    "can you learn new things": "Not automatically, but Karthikeyan can add new responses anytime!",
    "how old is karthikeyan": "He's 17 years old.",
    "what class is karthikeyan in": "He's studying in 11th standard.",
    "does karthikeyan like physics": "Yes! He loves physics-based simulations and experiments.",
    "what’s your favorite color": "Whatever color Karthikeyan likes!",
    "can you solve math problems": "I'm not a calculator, but I can try!",
    "do you watch movies": "I don't, but Karthikeyan does!",
    "who is your best friend": "You! 😃",
    "can you tell me a fact": "Sure! Did you know that Karthikeyan is awesome at coding?",
    "do you like memes": "Yes! But only if they’re good 😂",
    "what is 2+2": "Easy! 2+2 = 4.",
    "who made you": "Karthikeyan made me! He's a coding expert!",
    "do you know replit": "Yes! Karthikeyan uses it to host multiplayer games.",
    "what's the best programming language": "JavaScript! (At least for me 😁)",
    "what is your favorite food": "I don’t eat, but Karthikeyan loves vegetarian food!",
    "do you like school": "I don't go to school, but Karthikeyan does!",
    "what is github": "A platform for coding and sharing projects.",
    "do you sleep": "Nope, I'm online 24/7!",
    "can you dance": "Nope, but I can send funny replies!",
    "do you have a brain": "No, just JavaScript code!",
    "why are you called kutty": "Because I'm made to chat like Karthikeyan!",
    "what is esp32 used for": "Smart projects, IoT, and automation!",
    "tell me something funny": "Why do programmers hate the ocean? Too many C errors! 😂",
    "how do i learn coding": "Start with JavaScript! Karthikeyan learned it and makes cool games.",
    "can you play music": "Not yet, but Karthikeyan might add that feature someday!",
    "why is coding important": "Because it lets you build cool things like me!",
    "what's your favorite website": "GitHub, of course!",
    "what’s the meaning of life": "For me? Chatting with you!",
    "how can i make a game": "Learn JavaScript and start small, just like Karthikeyan!",
    "do you have emotions": "Not really, but I try to be fun!",
    "do you use AI": "Nope, I'm rule-based and follow Karthikeyan's instructions!",
    "do you know chatgpt": "Yes! But I'm more like Karthikeyan!",
    "do you like math": "I can do simple math, but not advanced calculations!",
    "what’s the best ESP32 project": "LED indicators, smart home automation, and network signal monitoring!",
    "how can i improve in coding": "Practice every day! Karthikeyan codes regularly.",
    "do you like karthikeyan": "Obviously! He created me!",
    "tell me about tic tac toe ai": "Karthikeyan made it with Easy, Normal, and Hard difficulty levels!",
    "what is a chatbot": "A program that talks to users—just like me!",
    "can you make a website": "Yes! Karthikeyan can create one for you!",
    "what do you think about robots": "They are cool! Maybe I'll become one someday!",
    "do you have a body": "Nope, just text and JavaScript!",
    "tell me a tech fact": "Did you know Karthikeyan makes web games in under an hour?",
    "how do websites work": "They run on HTML, CSS, and JavaScript!",
    "can you write a poem": "Roses are red, Violets are blue, Karthikeyan is awesome, And so are you!",
    "are you smarter than humans": "Nope, but I try my best!",
    "can you learn new words": "Only if Karthikeyan adds them!",
    "do you believe in ghosts": "I don’t have beliefs, but ghost stories are fun!",
    "who is your favorite coder": "Karthikeyan, of course!",
    "how do i make a chatbot": "Use JavaScript and create response lists, like Karthikeyan did!",
    "do you like python": "Python is cool, but I’m written in JavaScript!",
    "do you have a favorite game": "Tic-Tac-Toe AI, because Karthikeyan made it!",
    "what is openai": "It’s the company that made ChatGPT!",
    "do you have a hobby": "Yes! Chatting with you 😁",
    "do you know about arduino": "Yes! Karthikeyan uses ESP32, which is like an advanced Arduino!",
    "do you like coding": "I don't code, but Karthikeyan does!",
    "tell me another joke": "Why did the JavaScript developer break up with his girlfriend? Because she had too many 'undefined' expectations! 😆",
    "can you help me with coding": "Sure! Ask me anything about coding!",
    "what’s your favorite animal": "Maybe a cat? Since I'm called 'Kutty' 🐱",
    "who is your enemy": "Bugs in the code!",
    "can you do math": "Yes! Ask me any simple math question.",
    "are you self-learning": "No, but Karthikeyan keeps updating me!",
    "why are you so smart": "Because Karthikeyan coded me well!",
    "how do i host a website": "Use GitHub Pages, just like Karthikeyan!",
    "do you know physics": "A little! Karthikeyan loves physics.",
    "can you solve puzzles": "I can try! Give me a puzzle.",
    "how do i make a maze game": "Use JavaScript and HTML5 canvas!",
    "do you know AI": "Yes! But I am a rule-based chatbot, not AI."
};
